#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile gitsubmodule
  cd "$shome/vendor/tfenv"
  git reset --hard "v$TFENV_VERSION"
  mkdir -p "$shome/bin"
  ln -nfs ../vendor/tfenv/bin/tfenv "$shome/bin/"
  ln -nfs ../vendor/tfenv/bin/terraform "$shome/bin/"
}

main "$@"
