#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_tfenv="$(tfenv 2>&1 | head -1 | awk '{print $2}' || true)"
  jq -n --arg tfenv "$ver_tfenv" '{tfenv: $tfenv}'
}

version "$@"
