#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_tfenv="$(env USE_DEBUG=1 tfenv 2>/dev/null | head -1 | awk '{print $3}' || true)"
  jq -n --arg tfenv "$ver_tfenv" '{tfenv: $tfenv}'
}

version "$@"
